<?php

if (!defined('BASEPATH'))
	exit('No direct script access allowed');

class Jabatan extends CI_Controller
{
	function __construct()
	{
		parent::__construct();
		$this->load->model('Jabatan_model');
		$this->load->library('form_validation');
		$this->load->library('datatables');
	}

	public function index()
	{
		$this->load->view('template/header');
		$this->load->view('template/sidebar');
		$this->load->view('template/topbar');
		$this->load->view('jabatan/jabatan_list');
		// $this->load->view('template/footer');
	}

	public function json()
	{
		header('Content-Type: application/json');
		echo $this->Jabatan_model->json();
	}

	public function read($id)
	{
		$row = $this->Jabatan_model->get_by_id($id);
		if ($row) {
			$data = array(
				'id' => $row->id,
				'nama_jabatan' => $row->nama_jabatan,
			);
			$this->load->view('jabatan/jabatan_read', $data);
		} else {
			$this->session->set_flashdata('message', 'Record Not Found');
			redirect(site_url('jabatan'));
		}
	}

	public function create()
	{
		$data = array(
			'button' => 'Create',
			'action' => site_url('jabatan/create_action'),
			'id' => set_value('id'),
			'nama_jabatan' => set_value('nama_jabatan'),
		);
		$this->load->view('template/header');
		$this->load->view('template/sidebar');
		$this->load->view('template/topbar');
		$this->load->view('jabatan/jabatan_form', $data);
		$this->load->view('template/footer');
	}

	public function create_action()
	{
		$this->_rules();

		if ($this->form_validation->run() == FALSE) {
			$this->create();
		} else {
			$data = array(
				'nama_jabatan' => $this->input->post('nama_jabatan', TRUE),
			);

			$this->Jabatan_model->insert($data);
			$this->session->set_flashdata('message', 'Create Record Success');
			redirect(site_url('jabatan'));
		}
	}

	public function update($id)
	{
		$row = $this->Jabatan_model->get_by_id($id);

		if ($row) {
			$data = array(
				'button' => 'Update',
				'action' => site_url('jabatan/update_action'),
				'id' => set_value('id', $row->id),
				'nama_jabatan' => set_value('nama_jabatan', $row->nama_jabatan),
			);
			$this->load->view('template/header');
			$this->load->view('template/sidebar');
			$this->load->view('template/topbar');
			$this->load->view('jabatan/jabatan_form', $data);
			$this->load->view('template/footer');
		} else {
			$this->session->set_flashdata('message', 'Record Not Found');
			redirect(site_url('jabatan'));
		}
	}

	public function update_action()
	{
		$this->_rules();

		if ($this->form_validation->run() == FALSE) {
			$this->update($this->input->post('id', TRUE));
		} else {
			$data = array(
				'nama_jabatan' => $this->input->post('nama_jabatan', TRUE),
			);

			$this->Jabatan_model->update($this->input->post('id', TRUE), $data);
			$this->session->set_flashdata('message', 'Update Record Success');
			redirect(site_url('jabatan'));
		}
	}

	public function delete($id)
	{
		$row = $this->Jabatan_model->get_by_id($id);

		if ($row) {
			$this->Jabatan_model->delete($id);
			$this->session->set_flashdata('message', 'Delete Record Success');
			redirect(site_url('jabatan'));
		} else {
			$this->session->set_flashdata('message', 'Record Not Found');
			redirect(site_url('jabatan'));
		}
	}

	public function _rules()
	{
		$this->form_validation->set_rules('nama_jabatan', 'nama jabatan', 'trim|required');

		$this->form_validation->set_rules('id', 'id', 'trim');
		$this->form_validation->set_error_delimiters('<span class="text-danger">', '</span>');
	}
}

/* End of file Jabatan.php */
/* Location: ./application/controllers/Jabatan.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2024-10-26 03:48:04 */
/* http://harviacode.com */
