<?php

if (!defined('BASEPATH'))
	exit('No direct script access allowed');

class Jenis_cuti extends CI_Controller
{
	function __construct()
	{
		parent::__construct();
		check_not_login();
		$this->load->model('Jenis_cuti_model');
		$this->load->library('form_validation');
		$this->load->library('datatables');
	}

	public function index()
	{
		$this->load->view('template/header');
		$this->load->view('template/sidebar');
		$this->load->view('template/topbar');
		$this->load->view('jenis_cuti/jenis_cuti_list');
		$this->load->view('template/footer');
	}

	public function json()
	{
		header('Content-Type: application/json');
		echo $this->Jenis_cuti_model->json();
	}

	public function read($id)
	{
		$row = $this->Jenis_cuti_model->get_by_id($id);
		if ($row) {
			$data = array(
				'id' => $row->id,
				'nama_jenis_cuti' => $row->nama_jenis_cuti,
				'keterangan' => $row->keterangan,
				'durasi' => $row->durasi,
			);
			$this->load->view('jenis_cuti/jenis_cuti_read', $data);
		} else {
			$this->session->set_flashdata('message', 'Record Not Found');
			redirect(site_url('jenis_cuti'));
		}
	}

	public function create()
	{
		$data = array(
			'button' => 'Create',
			'action' => site_url('jenis_cuti/create_action'),
			'id' => set_value('id'),
			'nama_jenis_cuti' => set_value('nama_jenis_cuti'),
			'keterangan' => set_value('keterangan'),
			'durasi' => set_value('durasi'),
		);
		$this->load->view('template/header');
		$this->load->view('template/sidebar');
		$this->load->view('template/topbar');
		$this->load->view('jenis_cuti/jenis_cuti_form', $data);
		$this->load->view('template/footer');
	}

	public function create_action()
	{
		$this->_rules();

		if ($this->form_validation->run() == FALSE) {
			$this->create();
		} else {
			$data = array(
				'nama_jenis_cuti' => $this->input->post('nama_jenis_cuti', TRUE),
				'keterangan' => $this->input->post('keterangan', TRUE),
				'durasi' => $this->input->post('durasi', TRUE),
			);

			$this->Jenis_cuti_model->insert($data);
			$this->session->set_flashdata('message', 'Create Record Success');
			redirect(site_url('jenis_cuti'));
		}
	}

	public function update($id)
	{
		$row = $this->Jenis_cuti_model->get_by_id($id);

		if ($row) {
			$data = array(
				'button' => 'Update',
				'action' => site_url('jenis_cuti/update_action'),
				'id' => set_value('id', $row->id),
				'nama_jenis_cuti' => set_value('nama_jenis_cuti', $row->nama_jenis_cuti),
				'keterangan' => set_value('keterangan', $row->keterangan),
				'durasi' => set_value('durasi', $row->durasi),
			);
			$this->load->view('template/header');
			$this->load->view('template/sidebar');
			$this->load->view('template/topbar');
			$this->load->view('jenis_cuti/jenis_cuti_form', $data);
			$this->load->view('template/footer');
		} else {
			$this->session->set_flashdata('message', 'Record Not Found');
			redirect(site_url('jenis_cuti'));
		}
	}

	public function update_action()
	{
		$this->_rules();

		if ($this->form_validation->run() == FALSE) {
			$this->update($this->input->post('id', TRUE));
		} else {
			$data = array(
				'nama_jenis_cuti' => $this->input->post('nama_jenis_cuti', TRUE),
				'keterangan' => $this->input->post('keterangan', TRUE),
				'durasi' => $this->input->post('durasi', TRUE),
			);

			$this->Jenis_cuti_model->update($this->input->post('id', TRUE), $data);
			$this->session->set_flashdata('message', 'Update Record Success');
			redirect(site_url('jenis_cuti'));
		}
	}

	public function delete($id)
	{
		$row = $this->Jenis_cuti_model->get_by_id($id);

		if ($row) {
			$this->Jenis_cuti_model->delete($id);
			$this->session->set_flashdata('message', 'Delete Record Success');
			redirect(site_url('jenis_cuti'));
		} else {
			$this->session->set_flashdata('message', 'Record Not Found');
			redirect(site_url('jenis_cuti'));
		}
	}

	public function _rules()
	{
		$this->form_validation->set_rules('nama_jenis_cuti', 'nama jenis cuti', 'trim|required');
		$this->form_validation->set_rules('keterangan', 'keterangan', 'trim|required');
		$this->form_validation->set_rules('durasi', 'durasi', 'trim|required');

		$this->form_validation->set_rules('id', 'id', 'trim');
		$this->form_validation->set_error_delimiters('<span class="text-danger">', '</span>');
	}
}

/* End of file Jenis_cuti.php */
/* Location: ./application/controllers/Jenis_cuti.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2024-10-26 03:48:13 */
/* http://harviacode.com */
