<?php

if (!defined('BASEPATH'))
	exit('No direct script access allowed');

class Cuti_model extends CI_Model
{

	public $table = 'cuti';
	public $id = 'id';
	public $order = 'DESC';

	function __construct()
	{
		parent::__construct();
	}

	// datatables
	public function json()
	{
		$this->datatables->select('cuti.id, users.username as nama_user, jenis_cuti.nama_jenis_cuti, cuti.tanggal_pengajuan, cuti.tanggal_mulai, cuti.tanggal_selesai, cuti.lama_cuti, cuti.sisa_cuti, cuti.alasan, cuti.id_persetujuan, cuti.catatan_pimpinan');
		$this->datatables->from('cuti');

		// Join tabel 'users' dan 'jenis_cuti' dengan 'cuti'
		$this->datatables->join('users', 'cuti.id_user = users.id', 'left');
		$this->datatables->join('jenis_cuti', 'cuti.id_jenis_cuti = jenis_cuti.id', 'left');

		// Menambahkan kolom 'action' dengan tombol Edit dan Delete
		$this->datatables->add_column(
			'action',
			anchor(site_url('cuti/update/$1'), '<button class="btn btn-sm btn-success"><i class="fas fa-edit"></i> Edit</button>') . " " .
				anchor(site_url('cuti/delete/$1'), '<button class="btn btn-sm btn-danger"><i class="fas fa-trash"></i> Delete</button>', 'onclick="return confirm(\'Are you sure?\')"'),
			'id'
		);

		return $this->datatables->generate();
	}
	public function json_pegawai()
	{
		// Mendapatkan id_user dari sesi login
		$id_user = $this->session->userdata('user')->id;

		$this->datatables->select('cuti.id, users.username as nama_user, jenis_cuti.nama_jenis_cuti, cuti.tanggal_pengajuan, cuti.tanggal_mulai, cuti.tanggal_selesai, cuti.lama_cuti, cuti.sisa_cuti, cuti.alasan, cuti.id_persetujuan, cuti.catatan_pimpinan');
		$this->datatables->from('cuti');

		// Join tabel 'users' dan 'jenis_cuti' dengan 'cuti'
		$this->datatables->join('users', 'cuti.id_user = users.id', 'left');
		$this->datatables->join('jenis_cuti', 'cuti.id_jenis_cuti = jenis_cuti.id', 'left');

		// Menambahkan filter untuk hanya menampilkan data sesuai id_user yang sedang login
		$this->datatables->where('cuti.id_user', $id_user);

		// Menambahkan kolom 'action' dengan tombol Edit dan Delete
		$this->datatables->add_column(
			'action',
			anchor(site_url('cuti/update/$1'), '<button class="btn btn-sm btn-success"><i class="fas fa-edit"></i> Edit</button>') . " " .
				anchor(site_url('cuti/delete/$1'), '<button class="btn btn-sm btn-danger"><i class="fas fa-trash"></i> Delete</button>', 'onclick="return confirm(\'Are you sure?\')"'),
			'id'
		);

		return $this->datatables->generate();
	}



	// get all
	function get_all()
	{
		$this->db->order_by($this->id, $this->order);
		return $this->db->get($this->table)->result();
	}

	// get data by id
	function get_by_id($id)
	{
		$this->db->where($this->id, $id);
		return $this->db->get($this->table)->row();
	}

	// get total rows
	function total_rows($q = NULL)
	{
		$this->db->like('id', $q);
		$this->db->or_like('id_user', $q);
		$this->db->or_like('id_jenis_cuti', $q);
		$this->db->or_like('tanggal_pengajuan', $q);
		$this->db->or_like('tanggal_mulai', $q);
		$this->db->or_like('tanggal_selesai', $q);
		$this->db->or_like('lama_cuti', $q);
		$this->db->or_like('sisa_cuti', $q);
		$this->db->or_like('alasan', $q);
		$this->db->or_like('id_persetujuan', $q);
		$this->db->or_like('catatan_pimpinan', $q);
		$this->db->from($this->table);
		return $this->db->count_all_results();
	}

	// get data with limit and search
	function get_limit_data($limit, $start = 0, $q = NULL)
	{
		$this->db->order_by($this->id, $this->order);
		$this->db->like('id', $q);
		$this->db->or_like('id_user', $q);
		$this->db->or_like('id_jenis_cuti', $q);
		$this->db->or_like('tanggal_pengajuan', $q);
		$this->db->or_like('tanggal_mulai', $q);
		$this->db->or_like('tanggal_selesai', $q);
		$this->db->or_like('lama_cuti', $q);
		$this->db->or_like('sisa_cuti', $q);
		$this->db->or_like('alasan', $q);
		$this->db->or_like('id_persetujuan', $q);
		$this->db->or_like('catatan_pimpinan', $q);
		$this->db->limit($limit, $start);
		return $this->db->get($this->table)->result();
	}

	// insert data
	function insert($data)
	{
		$this->db->insert($this->table, $data);
	}

	// update data
	function update($id, $data)
	{
		$this->db->where($this->id, $id);
		$this->db->update($this->table, $data);
	}

	// delete data
	function delete($id)
	{
		$this->db->where($this->id, $id);
		$this->db->delete($this->table);
	}
}

/* End of file Cuti_model.php */
/* Location: ./application/models/Cuti_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2024-10-26 03:38:25 */
/* http://harviacode.com */
