<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Jenis_cuti_model extends CI_Model
{

    public $table = 'jenis_cuti';
    public $id = 'id';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // datatables
    function json() {
        $this->datatables->select('id,nama_jenis_cuti,keterangan,durasi');
        $this->datatables->from('jenis_cuti');
        //add this line for join
        //$this->datatables->join('table2', 'jenis_cuti.field = table2.field');
		$this->datatables->add_column(
			'action', 
			anchor(
				site_url('jenis_cuti/update/$1'), 
				'<button class="btn btn-sm btn-success"><i class="fas fa-edit"></i> Edit</button>'
			) . " " .
			anchor(
				site_url('jenis_cuti/delete/$1'), 
				'<button class="btn btn-sm btn-danger"><i class="fas fa-trash"></i> Delete</button>',
				'onclick="javascript: return confirm(\'Are you sure?\')"'
			), 
			'id'
		);
        return $this->datatables->generate();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id', $q);
	$this->db->or_like('nama_jenis_cuti', $q);
	$this->db->or_like('keterangan', $q);
	$this->db->or_like('durasi', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id', $q);
	$this->db->or_like('nama_jenis_cuti', $q);
	$this->db->or_like('keterangan', $q);
	$this->db->or_like('durasi', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Jenis_cuti_model.php */
/* Location: ./application/models/Jenis_cuti_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2024-10-26 03:48:13 */
/* http://harviacode.com */
