<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Pegawai_model extends CI_Model
{

    public $table = 'pegawai';
    public $id = 'id';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // datatables
	function json() {
		// Mengambil kolom dari tabel pegawai
		$this->datatables->select('pegawai.id, pegawai.id_user, pegawai.id_jabatan, pegawai.id_ruangan, pegawai.nip, pegawai.status_pegawai, pegawai.alamat, pegawai.tanggal_lahir, pegawai.jenis_kelamin, pegawai.telepon, pegawai.email, 
			ruangan.nama_ruangan, jabatan.nama_jabatan, users.nama as user_name');
		
		// Tabel utama
		$this->datatables->from('pegawai');
		
		// Join dengan tabel ruangan
		$this->datatables->join('ruangan', 'pegawai.id_ruangan = ruangan.id', 'left');
		
		// Join dengan tabel jabatan
		$this->datatables->join('jabatan', 'pegawai.id_jabatan = jabatan.id', 'left');
		
		// Join dengan tabel users
		$this->datatables->join('users', 'pegawai.id_user = users.id', 'left');
	
		// Menambahkan kolom aksi dengan tombol Update dan Delete
		$this->datatables->add_column('action', 
			anchor(site_url('pegawai/update/$1'), '<button class="btn btn-sm btn-success"><i class="fas fa-edit"></i> Edit</button>') . " " . 
			anchor(site_url('pegawai/delete/$1'), '<button class="btn btn-sm btn-danger"><i class="fas fa-trash"></i> Delete</button>', 'onclick="javascript: return confirm(\'Are you sure?\')"'), 
			'id'
		);
		
		return $this->datatables->generate();
	}
	

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id', $q);
	$this->db->or_like('id_user', $q);
	$this->db->or_like('id_jabatan', $q);
	$this->db->or_like('id_ruangan', $q);
	$this->db->or_like('nip', $q);
	$this->db->or_like('status_pegawai', $q);
	$this->db->or_like('alamat', $q);
	$this->db->or_like('tanggal_lahir', $q);
	$this->db->or_like('jenis_kelamin', $q);
	$this->db->or_like('telepon', $q);
	$this->db->or_like('email', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id', $q);
	$this->db->or_like('id_user', $q);
	$this->db->or_like('id_jabatan', $q);
	$this->db->or_like('id_ruangan', $q);
	$this->db->or_like('nip', $q);
	$this->db->or_like('status_pegawai', $q);
	$this->db->or_like('alamat', $q);
	$this->db->or_like('tanggal_lahir', $q);
	$this->db->or_like('jenis_kelamin', $q);
	$this->db->or_like('telepon', $q);
	$this->db->or_like('email', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Pegawai_model.php */
/* Location: ./application/models/Pegawai_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2024-10-26 03:48:23 */
/* http://harviacode.com */
